CREATE FUNCTION DBO.ADJUST_CPF_CNPJ(@CPF_CNPJ VARCHAR(MAX))
RETURNS VARCHAR(MAX)
AS BEGIN
	
	SET @CPF_CNPJ = @CPF_CNPJ

	IF (LEN(@CPF_CNPJ) <= 11) BEGIN
		SET @CPF_CNPJ = CAST(CAST(@CPF_CNPJ AS BIGINT)AS VARCHAR(MAX))
		SET @CPF_CNPJ = REPLICATE('0', 11-LEN(@CPF_CNPJ)) + @CPF_CNPJ
	END

	IF (LEN(@CPF_CNPJ) >= 12) BEGIN
		SET @CPF_CNPJ = CAST(CAST(@CPF_CNPJ AS BIGINT)AS VARCHAR(MAX))
		SET @CPF_CNPJ = REPLICATE('0', 14-LEN(@CPF_CNPJ)) + @CPF_CNPJ
	END

	RETURN @CPF_CNPJ

END

SELECT DBO.ADJUST_CPF_CNPJ('000000000000')