DECLARE @NAME VARCHAR(MAX)

SET @NAME = 'MATHEUS SANTOS DE SOUZA'

WHILE CHARINDEX(' ', @NAME) > 0 BEGIN
	
	SELECT SUBSTRING(@NAME, 1, CHARINDEX(' ', @NAME) - 1)

	SET @NAME = SUBSTRING(@NAME, CHARINDEX(' ', @NAME) + 1, LEN(@NAME))

	IF CHARINDEX(' ', @NAME) = 0

	SELECT @NAME

END