CREATE FUNCTION DBO.REMOVE_ESPECIALS(@VARCHAR VARCHAR(MAX))
RETURNS VARCHAR(MAX)
AS BEGIN

	DECLARE @ESPECIALS VARCHAR(MAX) =  'אבגדהוחטיךכלםמןעףפץצשתûüְֱֲֳִֵַָֹÊֻּֽ־ֿׂ׃װױײÙÚÛÜ-'
	DECLARE @TEXT VARCHAR(MAX) = 'aaaaaaceeeeiiiiooooouuuuAAAAAACEEEEIIIIOOOOOUUUU '

	DECLARE @C INT = LEN(@VARCHAR)

	WHILE @C >= 1 BEGIN
		
		IF (CHARINDEX(SUBSTRING(@VARCHAR, @C, 1), @ESPECIALS) > 0) BEGIN
			
			SET @VARCHAR = REPLACE(@VARCHAR, SUBSTRING(@VARCHAR, @C, 1), SUBSTRING(@TEXT, @C, 1))

		END

		SET @C -= 1

	END

	RETURN @VARCHAR 

END

--SELECT DBO.REMOVE_ESPECIALS('אבגדהוחטיךכלםמןעףפץצשתûüְֱֲֳִֵַָֹÊֻּֽ־ֿׂ׃װױײÙÚÛÜ-')