USE SQL_DB_1

CREATE TABLE STOCK(
	ID_PRODUCT INT IDENTITY(1, 1),
	PRODUCT VARCHAR(MAX),
	QUANTITY INT,
	DATE_MODIFICATION DATETIME
)

INSERT INTO STOCK (PRODUCT, QUANTITY, DATE_MODIFICATION)
	VALUES('CHEESE', 89, GETDATE())

CREATE TABLE SALES(
	ID_PRODUCT INT IDENTITY(1, 1),
	PRODUCT VARCHAR(MAX),
	QUANTITY INT,
	DATE_SALE DATETIME
)

INSERT INTO SALES (PRODUCT, QUANTITY, DATE_SALE)
	VALUES('CHEESE', 11, GETDATE())


CREATE TRIGGER DELETED_SALES
ON SALES
AFTER DELETE
AS 
BEGIN
		DECLARE @ID_PRODUCT INT,
			@PRODUCT VARCHAR(MAX),
			@QUANTITY INT

			SELECT @ID_PRODUCT = ID_PRODUCT, @PRODUCT = PRODUCT, @QUANTITY = QUANTITY FROM DELETED

			UPDATE STOCK SET
				QUANTITY = QUANTITY + @QUANTITY
			WHERE 
				ID_PRODUCT = @ID_PRODUCT
			
END

SELECT * FROM STOCK
SELECT * FROM SALES

DELETE FROM SALES WHERE ID_PRODUCT = '1'

-- DROP TABLE STOCK
-- DROP TABLE SALES